# 如果你需要設定 GitHub 贊助渠道，取消下方對應選項的註解並填入你的資訊

# github: [你的GitHub用戶名]
# patreon: # 替換為你的 Patreon 用戶名
# open_collective: # 替換為你的 Open Collective 用戶名
# ko_fi: # 替換為你的 Ko-fi 用戶名
# tidelift: # 'npm/資源包名稱'
# community_bridge: # 替換為你的 Community Bridge 專案名稱
# liberapay: # 替換為你的 Liberapay 用戶名
# issuehunt: # 替換為你的 IssueHunt 用戶名
# otechie: # 替換為你的 Otechie 用戶名
# lfx_crowdfunding: # 替換為你的 LFX Crowdfunding 專案名稱
# custom: # 替換為最多4個自定義贊助URL的數組，例如['link1', 'link2']
